### PR TITLE
add UTXO Global Wallet

### PR DESCRIPTION
**Pull request by trongdth**
Add UTXO Global Wallet to the Wallet page

- Website: https://utxo.global/
- X: https://x.com/UTXOGlobal
- Chrome Wallet Extension: https://chromewebstore.google.com/detail/utxo-global-wallet/lnamkkidoonpeknminiadpgjiofpdmle

### CODE REVIEW

**Comment by Keith-CY** [comment]
#### 📝 Changed routes:


| [**/wallets/icons**](https://nervos-official-website-pkunmeore-magickbase.vercel.app/wallets/icons) | [**/wallets/icons/utxoGlobal**](https://nervos-official-website-pkunmeore-magickbase.vercel.app/wallets/icons/utxoGlobal) |
|:-:|:-:|
|<a href="https://nervos-official-website-pkunmeore-magickbase.vercel.app/wallets/icons">Screenshot of /wallets/icons</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/l_Pbd3do8SQ0oG4E25Yfc8cgcJhH5IAlhtMX3-6H8IWzGC0wQSpkIuAqGIwy1uf5iLYbj3kuw03TdJyAEWdc6w.png">(view full size)</a> |<a href="https://nervos-official-website-pkunmeore-magickbase.vercel.app/wallets/icons/utxoGlobal">Screenshot of /wallets/icons/utxoGlobal</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/lPMToyALJaRU5EbuRASUfecBZx-YEWj90OWI48lHmQowrO1v8_L13Jb5RkburbkO0XdOXEqaWyxQejLk_KwIIg.png">(view full size)</a> |



| [**/wallets/index.page**](https://nervos-official-website-pkunmeore-magickbase.vercel.app/wallets/index.page) |
|:-:|
|<a href="https://nervos-official-website-pkunmeore-magickbase.vercel.app/wallets/index.page">Screenshot of /wallets/index.page</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/IkaUp5yMfcYVcU3Osxj1xo1mfKfCZaR3IQKDhFEENamPgSFgcaiATzYPYv7zOJO0Tn3xxurbi3geSkb3MPNBww.png">(view full size)</a> |







Commit 089c7294d5db59cd07d3177e234a7bf62e727bc2 (https://nervos-official-website-pkunmeore-magickbase.vercel.app).

**Comment by trongdth** [comment]
I hope you can help to review it @Keith-CY

**Comment by Keith-CY** [comment]
@matt-nervos please have a review at https://nervos-official-website-git-fork-trongdth-develop-magickbase.vercel.app/wallets#utxo_global_wallet

**Comment by Matt-RUN-CKB** [comment]
looks good to me @Keith-CY

**Review by Keith-CY — APPROVED** [review]

**Pull request merged**
