### PR TITLE
feat: add imkey on the wallets page

### PR DESCRIPTION
**Pull request by Keith-CY**
Add `imKey` on the wallets page based on info at https://github.com/Magickbase/nervos-official-website/pull/509#issue-2604494115

### CODE REVIEW

**Comment by Keith-CY** [comment]
#### 📝 Changed routes:


| [**/wallets/icons/imKey**](https://nervos-official-website-28x27eifu-magickbase.vercel.app/wallets/icons/imKey) | [**/wallets/icons**](https://nervos-official-website-28x27eifu-magickbase.vercel.app/wallets/icons) |
|:-:|:-:|
|<a href="https://nervos-official-website-28x27eifu-magickbase.vercel.app/wallets/icons/imKey">Screenshot of /wallets/icons/imKey</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/hRCBo-xKsIx-q53dtKvU2g3UdOtyO3gGvZInv3kHpM_1Tk8ltDmL9f-modfznPOccb2xrqIWhdMQpRNLnWj-nw.png">(view full size)</a> |<a href="https://nervos-official-website-28x27eifu-magickbase.vercel.app/wallets/icons">Screenshot of /wallets/icons</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/xDfDIy-W9S4OT7gwPl5o7Cr-GYqHG6J5ldkB8NQXNOf8MZYjYaFtOCMmA6zZI4vCNUxNDKxfe7rfMYvgpfK-gg.png">(view full size)</a> |



| [**/wallets/icons/utxoGlobal**](https://nervos-official-website-28x27eifu-magickbase.vercel.app/wallets/icons/utxoGlobal) | [**/wallets/index.page**](https://nervos-official-website-28x27eifu-magickbase.vercel.app/wallets/index.page) |
|:-:|:-:|
|<a href="https://nervos-official-website-28x27eifu-magickbase.vercel.app/wallets/icons/utxoGlobal">Screenshot of /wallets/icons/utxoGlobal</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/3sUw6o-QUMeLF9NccfbpJHQIy3hyn5Z6iX704FSLemYEARnXCiQpq9H-vEsf90vb0eIGK58vbd1ZGi_xnlScpQ.png">(view full size)</a> |<a href="https://nervos-official-website-28x27eifu-magickbase.vercel.app/wallets/index.page">Screenshot of /wallets/index.page</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/oT_vj9yelFYMd7QzLigt4Hw-1DKYQIvfG3wWtsPSmIqgXu9jhv3d1kEEnpD8AvkAUbrjb9eCyXYG2klpoUwqRg.png">(view full size)</a> |







Commit b96b38b9c4b7cabba42c46545b88091e55bf7ec4 (https://nervos-official-website-28x27eifu-magickbase.vercel.app).

**Comment by Keith-CY** [comment]
Please have a review at https://nervos-official-website-git-add-imkey-magickbase.vercel.app/wallets#imkey
@matt-nervos

**Comment by Matt-RUN-CKB** [comment]
"free sending, and receiving of CKB"

"free" is awkward here, do you know what it is intended to mean? Maybe we can just remove that word @Keith-CY

**Comment by Keith-CY** [comment]
> "free sending, and receiving of CKB"
> 
> "free" is awkward here, do you know what it is intended to mean? Maybe we can just remove that word, otherwise it looks ok @Keith-CY

It was meant to be `easy`, `unfettered`, and was removed after being confirmed with the marketing team

**Pull request merged**
